configuration: Release

platform: Any CPU

image: Visual Studio 2017

environment:
    EnableNuGetPackageRestore: true

install:
    - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
    - nuget restore
    - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
    - ps: Vsix-TokenReplacement source\AssemblyInfo.Common.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build:
    project: BracketPairColorizer.sln
    verbosity: minimal

branches:
    only:
    - develop

after_test:
    - ps: Vsix-PushArtifacts | Vsix-PublishToGallery